### ISSUE TITLE
Installment Payments with Mollie

### ISSUE THREAD

**Issue by LeonBuchner** [mollie/laravel-cashier-mollie#131]
Hello,
I want to charge a big amount in multiple smaller amounts every month. For example the customer buys a 5000$ product I want to charge him 1000$ every month for 5 months.

I found in the documentation of mollie that there is a "times" parameter for that: https://docs.mollie.com/reference/v2/subscriptions-api/create-subscription

But how can I use it with the laravel package? I found nothing in the documentation or in other issues here.

**Comment by sandervanhooft** [comment]
Hi @LeonBuchner ,

Simply put, `instalments` (or `times`) are not supported.

Cashier Mollie leverages Mollie's payments API instead of the Subscriptions API. I have added "instalments/`times`"  to our idea list for v3, but there's not guarantee or timeline here as I suspect it involves a little more complexity than meets the eye.
