### ISSUE TITLE
Add Plan::times attribute

### ISSUE THREAD

**Issue by JessedeB** [mollie/laravel-cashier-mollie#134]
https://github.com/laravel/cashier-mollie/issues/115

The use case has been asked before, however this question is 3yrs old and I'm not aware of any updates on this so far.

**Comment by Naoray** [comment]
Hello @JessedeB,

I apologize for not answering earlier! Currently, we don't have the ability to support the `times` property. As described in the linked issue, we are not using Mollie’s subscription API in laravel-cashier-mollie because of its limitations.

However, I do understand that this feature would be valuable to you, and I want to let you know that we are actively working on implementing it. I have added this to our list of tasks for a future version, so please stay tuned for updates. Thank you for your patience and understanding!

**Comment by Naoray** [comment]
closing this for now
