### ISSUE TITLE
Please add a solid example for Coupons from database

### ISSUE THREAD

**Issue by ixperiencenl** [mollie/laravel-cashier-mollie#143]
The documentation / implementation for getting plans from the DB is quite straightforward. However, for coupons it's quite a bit different and hard to get around. Can you show a basic custom model that retrieves coupons from the database instead of the config file? Would be of great help.

**Comment by sandervanhooft** [comment]
Hi @ixperiencenl ,

What have you tried so far?

**Comment by ixperiencenl** [comment]
I tried making a custom Coupon model. Just as I created a custom Subscription. However, it looks like the coupons are different in structure than the Subscriptions.

My subscription Model:

`namespace App\Models\Cashier;

use Laravel\Cashier\Subscription as CashierSubscription;

class Subscription extends CashierSubscription
{
    protected $table = 'subscriptions';
}
`

Now, I think it's just almost the same for the Coupon, but that is not the case:
`namespace App\Models;

use Laravel\Cashier\Coupon\BaseCouponHandler as CashierCoupon;
use Laravel\Cashier\Order\OrderItemCollection;

class Coupon extends CashierCoupon
{
    protected $connection = 'mysql';
    protected $table = 'coupons';

    public function getDiscountOrderItems(OrderItemCollection $items)
    {
        
    }

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'amount' => 'array',
        'first_payment_amount' => 'array',
        'first_payment_method' => 'array',
        'meta' => 'array',
    ];
}`

In the docs, it says you need to extend the \Cashier\Discount\BaseCouponHandler which I did, but I cannot find logic methods that I want to use and also there is no explanation of which tables / columns needed.

**Comment by Naoray** [comment]
Hello @ixperiencenl,

I apologize for the delayed response!

If you wish to retrieve coupons from the database instead of a configuration file, you can create your own version of the `CouponRepository`. Here's an example implementation:

```php
<?php

namespace App;

use App\Models\Coupon as CouponModel;
use Exception;
use Laravel\Cashier\Coupon\Contracts\CouponRepository as CouponRepositoryContract;
use Laravel\Cashier\Coupon\Coupon;
use Laravel\Cashier\Coupon\FixedDiscountHandler;
use Laravel\Cashier\Coupon\PercentageDiscountHandler;
use Laravel\Cashier\Exceptions\CouponNotFoundException;

class CouponRepository implements CouponRepositoryContract
{
    /**
     * @param  string  $coupon
     * @return Laravel\Cashier\Coupon\Coupon|null
     */
    public function find(string $coupon)
    {
        $couponModel = CouponModel::where('code', $coupon)->first();

        if (!$couponModel) {
            return null;
        }

        $handler = match ($couponModel->type) {
            'fixed' => new FixedDiscountHandler(),
            'percentage' => new PercentageDiscountHandler(),
            default => throw new Exception('Invalid coupon type')
        };

        return new Coupon($coupon, $handler, $couponModel->context);
    }

    /**
     * @param  string  $coupon
     * @return Laravel\Cashier\Coupon\Coupon
     *
     * @throws CouponNotFoundException
     */
    public function findOrFail(string $coupon)
    {
        $result = $this->find($coupon);
        throw_if(is_null($result), CouponNotFoundException::class);

        return $result;
    }
}
```

Next, register your repository as a singleton in your `AppServiceProvider`.

```php
// AppServiceProvider

use App\CouponRepository;
use Laravel\Cashier\Coupon\Contracts\CouponRepository as CouponRepositoryContract;

public function register()
{
    $this->app->singleton(CouponRepositoryContract::class, CouponRepository::class);
}
```

Now, every time a coupon is retrieved, it will come from the database. The database migration should look like this:

```php
Schema::create('coupons', function (Blueprint $table) {
    $table->id();
    $table->string('code')->unique();
    $table->string(‘description’);
    $table->string('type');
    $table->json('context');
    $table->timestamps();
});
```

In this example, `code` is the unique code of the coupon, `type` is either percentage or fixed (assuming you want to reuse the available coupon handlers), and `context` is an array or object containing the same information that is currently in `cashier_coupons.{coupon_name}.context`.

If you only want to use one type of `CouponHandler` or want to create your own, you can define the required database schema yourself. The only requirement is that you can return a `Laravel\Cashier\Coupon\Coupon` instance from your `CouponRepository` and that the associated handler can parse the information you have given it.

Let me know if you have any further questions!
