### ISSUE TITLE
Subscription Trials is not working

### ISSUE THREAD

**Issue by pepijndik** [mollie/laravel-cashier-mollie#149]
I have configured my Model to be a billable model, with the required fields. But when I create a subscription for my model. It isn't  going for a trial but redirects to the Mollie payment ... 
when I check the ```php $user->onTrial(); ``` it returns true so somewhere  its not getting the correct values???
Hope someone can tell me whether I configured something wrong or this is just a bug
And when dump and die in de FirstPaymentSubscription builder (where the create method is for the new subscription) on the ```php  $this->isTrial ``` is then false??
```php
protected $fillable = [
        'id',
        'trial_ends_at',
        'email',
        'mollie_customer_id',
        'mollie_mandate_id',
        'name',
        'email_verified_at'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
        'trial_ends_at'
    ];
```
My Subscriptioncontroller 
```php
 $user->trial_ends_at = now()->addDays(14), //For no Payment details upfront needed
  try {
            $name = ucfirst($plan->name) . '_subscription';

            $result = $user->newSubscription('main', $plan->name)->create();

            return [
                'payment' => $result->payment()->getCheckoutUrl(),
                'message' => 'Subscription created successfully',
                'status' => 'success',
            ];

        } catch (InvalidMandateException|PlanNotFoundException$e) {
        }
```

**Comment by sandervanhooft** [comment]
Hi @pepijndik ,

This is by design.

Unless you're using a [generic trial](https://www.cashiermollie.com/03-trials.html#without-mandate-upfront), the customer will be redirected to Mollie's checkout to perform a minimum payment in order to generate a payment mandate.

If a mandate is already present, the customer doesn't need to go through the Mollie checkout.

By the way, there is no need to set the `trial_ends_at` on the billable model. This should suffice:

```php
$result = $user->newSubscription('main', $plan->name)->trialDays(14)->create();
```

**Comment by pepijndik** [comment]
>
