### ISSUE TITLE
Questions about integrating the package

### ISSUE THREAD

**Issue by michelterstege81** [mollie/laravel-cashier-mollie#151]
Hi,

I'm currently trying to integrate the package (which I think is great by the way), however I'm running into a few things I can't find answers on in the documentation:

- I would like to invoice at the first of the month. The so called 'anchoring the billing cycle'. As described here: https://github.com/laravel/cashier-mollie/issues/66. Is this currently possible?
- I also would like to apply metered billing based on the resources used in the past month. I read on https://www.cashiermollie.com/12-faq.html#how-is-prorating-handled that "Cashier Mollie applies prorating by default. With prorating, customers are billed at the start of each billing cycle." So is it possible to change this default?
- I develop on localhost. Is it possible to test on localhost? Maybe not even the connection with Mollie, but to generate some subscriptions and orders, so I can test for example how an invoice looks like or testing a page that lists the invoices?

Kind regards

**Comment by Naoray** [comment]
Hi @michelterstege81,

sorry for taking so long to answer your questions!

> I would like to invoice at the first of the month. The so called 'anchoring the billing cycle'. As described here: https://github.com/laravel/cashier-mollie/issues/66. Is this currently possible?

Anchor billing is not supported out of the box by laravel-cashier-mollie. However, you can create your own `AnchoredIntervalGenerator` class that implements the `Laravel\Cashier\Plan\Contracts\IntervalGeneratorContract` interface. In your `cashier_plans.php` file you can then configure your plan to use this generator. The next version of this package will likely contain this `IntervalGenerator` out of the box.

An example of an implementation for the `AnchoredIntervalGenerator` could look like the following:

```php
<?php

use Carbon\Carbon;
use Illuminate\Support\Str;
use Illuminate\Support\Arr;
use Laravel\Cashier\Plan\Contracts\IntervalGeneratorContract;
use Laravel\Cashier\Subscription;
use Laravel\Cashier\Plan\BaseIntervalGenerator;

class AnchoredIntervalGenerator extends BaseIntervalGenerator implements IntervalGeneratorContract
{
    /**
     * @var array
     */
    protected array $configuration;

    public function __construct(array $configuration)
    {
        $this->configuration = $configuration;

        $this->useCarbonGivenDayOrLast();
    }

    /**
     * @param  \Laravel\Cashier\Subscription  $subscription
     * @return \Carbon\Carbon
     */
    public function getEndOfNextSubscriptionCycle(Subscription $subscription = null)
    {
        $cycle_ends_at = $subscription->cycle_ends_at ?? now();

        if ($this->isMonthly()) {
            return $cycle_ends_at
                ->addMonthNoOverflow()
                ->setDaysToGivenDayOrLastOfMonth($this->day());
        }

        $endOfNextSubscriptionCycle = $cycle_ends_at->month($this->month());

        if ($endOfNextSubscriptionCycle->isPast()) {
            $endOfNextSubscriptionCycle = $endOfNextSubscriptionCycle = $endOfNextSubscriptionCycle->addYearNoOverflow();
        }

        return $endOfNextSubscriptionCycle->setDaysToGivenDayOrLastOfMonth($this->day());
    }

    /**
     * @return int|string
     */
    protected function day()
    {
        return Arr::get($this->configuration, 'day');
    }

    /**
     * @return int
     */
    protected function month(): int
    {
        $month = Arr::get($this->configuration, 'month', 1);

        return $month > 12 ? 12 : $month;
    }

    /**
     * @return string
     */
    protected function period(): string
    {
        return Arr::get($this->configuration, 'period');
    }

    /**
     * @return bool
     */
    protected function isMonthly(): bool
    {
        return Str::startsWith($this->period(), 'month');
    }

    private function useCarbonGivenDayOrLast(): void
    {
        Carbon::macro('setDaysToGivenDayOrLastOfMonth', function (int|string $day) {
            if (in_array($day, ['end', 'last']) || $day > $this->daysInMonth) {
                $day = $this->daysInMonth;
            }

            return $this->day($day);
        });
    }
}
```

An example configuration to anchor the billing cycle to the first of the month would be

```php
// config/cashier_plans.php
[
    // ...

    ‘plans’ => [
        ‘example_1’ => [
            // ...
    
            ‘interval’ => [
                'generator' => AnchoredIntervalGenerator::class,
                'day' => 1,
                'period' => 'month',
            ],
            
            // …
]
```

This will only ensure that the billing date is anchored to the first of the month, but it will not adapt the price for an incomplete first interval.

—

> I also would like to apply metered billing based on the resources used in the past month. I read on https://www.cashiermollie.com/12-faq.html#how-is-prorating-handled that "Cashier Mollie applies prorating by default. With prorating, customers are billed at the start of each billing cycle." So is it possible to change this default?

Prorating refers to the calculation of charges based on partial usage, and it does not determine when a user will be billed. In other words, prorating ensures that customers are charged only for the resources they have used in a billing cycle, regardless of when the billing cycle begins or ends.

You can implement metered billing by configuring the `order_item_preprocessors` in your `cashier_plans` config. A `MeteredBillingPreprocessor` could look something like the following:

```php
use Laravel\Cashier\Order\BaseOrderItemPreprocessor;
use Laravel\Cashier\Order\OrderItem;
use Laravel\Cashier\Order\OrderItemCollection;

class MeteredBillingPreprocessor extends BaseOrderItemPreprocessor
{
    /**
     * @param  \Laravel\Cashier\Order\OrderItemCollection  $items
     * @return \Laravel\Cashier\Order\OrderItemCollection
     */
    public function handle(OrderItemCollection $items)
    {
        // You can add, remove or modify order items here.
        // Each order item relates to 1 line on the invoice.
        
        // For metered billing, you typically:
        // 1. fetch metered data from within your app
        // 2. apply it to the order items
        // 3. if necessary, notify the meters that the costs were incurred/reset the meters
        
        $owner = $items->owners()->first();
        
        $meters = $owner->getMeters();
        $meterItems = $meters->map(function ($meter) {
            return OrderItem::make([
                'process_at' => now(),
                'description' => $meter->description,
                'currency' => $meter->currency,
                'unit_price' => $meter->unit_price,
                'quantity' => $meter->quantity,
                'tax_percentage' => $this->tax_percentage, 
            ]);
        });
        
        $items = $items->concat($meterItems);
        
        $owner->resetMeters(); // optionally put this in a separate ResetMetersPreprocessor right after the PersistOrderItemsPreprocessor
        
        return $items;
    }
}
```

Note that at this time it is not possible to add preprocessors to the first payment. This means you still have to reimburse the user for the first billing cycle for the amount he overpaid.

—

> I develop on localhost. Is it possible to test on localhost? Maybe not even the connection with Mollie, but to generate some subscriptions and orders, so I can test for example how an invoice looks like or testing a page that lists the invoices?

To test the integration with Mollie and Cashier, you can use a test API key provided by Mollie and make your webhook URL available to the Mollie app.

To obtain a test API key, you can navigate to the Developers section of your Mollie account dashboard and select API keys. From there, locate the key with the test_ prefix, copy it, and paste it into your .env file under MOLLIE_KEY.

Expose your app to mollie by running the `valet share` command (Laravel Valet). Otherwise, you can use tools like [Expose](https://expose.dev/docs/introduction) or ngrok.

The process is then to 
1. create a subscription like shown in the [documentation example](https://www.cashiermollie.com/02-subscriptions.html#creating-subscriptions)
2. go to the returned url and execute the payment of the subscription (it will show that testmode is activated)
3. wait for the webhook request for your payment
4. find the order that was created for your subscription and get the invoice

```php
$order = $user->orders()->first();

$user->findInvoice($order->number);
```

If you want only to see how the design of an invoice looks, I would recommend you to just manually create an order Item and use it to setup the order to retrieve the invoice:

```php
Route::get(‘/invoice', function () {
    $user = User::first();

    $orderItemsCollection = $user->orderItems()->create([
        'process_at' => now(),
        'description' => 'test',
        'currency' => 'EUR',
        'unit_price' => 2499,
        'tax_percentage' => 0.19,
        'quantity' => 1,
    ])->toCollection();
    
    $order = Order::createFromItems($orderItemsCollection);

    return $order->invoice()->download();
});


—

I am currently gathering all the necessary information to answer your second question, and will get back to you as soon as possible.

**Comment by michelterstege81** [comment]
Thanks for the very comprehensive answer!

I'm currently working on another project, but I'll definitely be working on this one soon.

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
