### ISSUE TITLE
Customer Credit in cents?

### ISSUE THREAD

**Issue by tobischulz** [mollie/laravel-cashier-mollie#180]
I have added a credit about 300 for a customer. In the database the column value holds the value "300". On other already existing credits the value is not in full euros, they are in cents. So to add a credit about 300 € the value column should be 30000 instead. Or am i wrong?

![CleanShot 2023-06-23 at 09 23 59](https://github.com/mollie/laravel-cashier-mollie/assets/576014/1c574cdc-a115-4941-8e72-5a7aede3f16d)

If this example about 10 € is not wrong... some customers have a credit about **42.387,00** € instead of **423,87€**.

Im confused. Please help.

**Comment by Naoray** [comment]
Hi @tobischulz,

thanks for bringing this to out attention!

The documentation for adding credits to a user are wrong by a factor of 100. In the example that is provided in the docs, instead of adding 10 € it would only add 0.10 € to the user’s balance

I apologise for any confusion or inconvenience this may have caused. I’ll make sure to fix the docs ASAP.

If you have any further questions or need assistance with anything else, please feel free to let me know.

**Comment by tobischulz** [comment]
Thank you! 
Thats all thanks. Have a nice weekend. 🫶

**Comment by sandervanhooft** [comment]
The updated docs were just deployed. Thanks @tobischulz and @Naoray !
