### ISSUE TITLE
Cannot set the period limit

### ISSUE THREAD

**Issue by handhikadj** [mollie/laravel-cashier-mollie#196]
I can't find any reference on how to set the period limit.
This will monthly-bill the user endlessly:
```php
public function buildCashierPlan(): Plan
    {
        $plan = new Plan($this->name);

        $amount = [
            'value' => 50.00,
            'currency' => 'EUR'
        ];

        return $plan->setAmount(mollie_array_to_money($amount))
            ->setInterval('1 month')
            ->setDescription('Pay description')
            ->setFirstPaymentMethod([])
            ->setFirstPaymentAmount(mollie_array_to_money($amount))
            ->setFirstPaymentDescription('Pay description')
            ->setFirstPaymentRedirectUrl(config('app.front_end_url') . '/premium?success=true')
            ->setFirstPaymentWebhookUrl(config('cashier.first_payment.webhook_url'));
    }
```
related: https://github.com/laravel/cashier-mollie/issues/115
any reference / workaround?

**Comment by Naoray** [comment]
Hi @handhikadj,

I’ve noted down that the times-feature is highly requested and I will work on it as soon as possible.

Meanwhile you can implement a workaround yourself by
1. Implementing your own `Plan` Model which offers a `times` column -> I believe based on your code piece, that you followed the examples from the docs on how to load your [plans from the database](https://www.cashiermollie.com/12-faq.html#how-can-i-load-coupons-and-or-plans-from-the-database). Only thing that you has to change is to let your `Plan` model implement the `\Laravel\Cashier\Plan\Contracts\Plan` contract
2. Add a `times` column to your `Subscription` model
3. Listen to `OrderPaymentPaid` and increment your `Subscription`’s `times` column with `$event->order->orderItems->first()->orderable->increment(’times’)` 
4. Instead of calling `cashier::run` from your console kernel directly, you have to create your own job/command which (1) queries Subscriptions, (2) checks if there plan’s `times` equals the subscription’s `times`

```php
use Laravel\Cashier\Cashier;
use App\Models\Subscription;

Subscription::whereActive()
    ->cursor()
    ->each(function (Subscription $subscription) {
        if ($subscription->times === $subscription->plan()->times) {
            $subscription->cancel();
        }
    });

Cashier::run();
```

If you have questions, please let me know!
