### ISSUE TITLE
Why not use the Subscription API?

### ISSUE THREAD

**Issue by handhikadj** [mollie/laravel-cashier-mollie#197]
how this package handles stuff manually doesn't make any sense since Mollie already have the Subscription API.
what is the motive behind this?
anyway, can I easily switch to Subscription API while using this package?

**Comment by sandervanhooft** [comment]
Mollie's Subscription API provides very basic features compared to this package. Prorating etc. is not possible on the Subscription API, that's why Cashier Mollie is handling the scheduling itself, triggering payments on the Payment API.

If you feel the Subscription API is a good fit for you, you can use the mandateIds stored on Cashier to initiate the subscriptions using the Subscription API.

You could use one of these packages:

- `mollie/mollie-api-php` (the core PHP SDK)
- `mollie/laravel-mollie`. This is essentially a wrapper around the PHP SDK, wiring up authentication for you.

You can simply copy-paste samples from the [Mollie docs](https://docs.mollie.com/reference/v2/subscriptions-api/overview) to work with either of these.

The [Subscriptions guide](https://docs.mollie.com/payments/recurring#payments-recurring-first-payment) may also be of interest to you.

**Comment by melnikanton** [comment]
do you mean that there's no way to easily switch to Subscription API while still using this package?
I already implemented Cashier but as it turns out Cashier doesn't store the Subscriptions that's why I can't see the Subscriptions on Mollie dashboard.

**Comment by handhikadj** [comment]
do you mean that there's no way to easily switch to Subscription API while still using this package?
I already implemented Cashier but as it turns out Cashier doesn't store the Subscriptions that's why I can't see the Subscriptions on Mollie dashboard.

**Comment by sandervanhooft** [comment]
Cashier is not using the Subscriptions API, but the Payments API. So the payments are showing up in Mollie's dashboard, just not as subscriptions.

If your app is live already, it's probably hard(er) to switch to the Subscriptions API. Otherwise it's definitely doable.

I suggest to first double check all your requirements (prorating, first payment flow, invoice generation etc) against the Subscriptions API features before considering the change.

**Comment by handhikadj** [comment]
is there any chance in the (near) future to integrate Subscription API to this package as opt-in feature?
something like this would be very great:
```php
// AppServiceProvider.php
Cashier::useSubscriptionApi();
```

**Comment by sandervanhooft** [comment]
Hi @handhikadj ,

That is not going to happen.
