### ISSUE TITLE
Double orders and orderItems for onetime-payments

### ISSUE THREAD

**Issue by lambertbeekhuis** [mollie/laravel-cashier-mollie#199]
When I follow the tutorial on https://sandorian.com/blog/announcing-laravel-cashier-mollie-v2 about one-time payments, it is making double orders and order-items.

In my case, the user does not have a mandate yet, so goes through the mollie-request.

(For subscription I see double orders as well, but one is for the next billing-cycle)

Any suggestions where this coming from, or is it as intended?

(subscriptions do work, and I do get an error:
 
Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view.. Field: webhookUrl. Documentation: https://docs.mollie.com/reference/v2/payments-api/update-payment

Do not know whether is related to this onetime, of previous subscriptions (There is no webhook_url for payment_update in the cashier)

So I am little lost.

Hope someone can help on this

**Comment by Naoray** [comment]
Hi @lambertbeekhuis,

> When I follow the tutorial on https://sandorian.com/blog/announcing-laravel-cashier-mollie-v2 about one-time payments, it is making double orders and order-items.
> 
> In my case, the user does not have a mandate yet, so goes through the mollie-request.

Are you talking about the one-off charges feature that is shown with sample code in the linked article? If so, the code from the tutorial creates two OrderItems, since we are adding two ChargeItem’s for the one-off charge. It only creates one Order for those two OrderItems when I ran the tutorial code.

Can you paste the code you used for the one-off charges and also your `cashier.php` config please?

> (For subscription I see double orders as well, but one is for the next billing-cycle)

Can you provide more context for this?

> (subscriptions do work, and I do get an error:
> 
> Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view.. Field: webhookUrl. Documentation: https://docs.mollie.com/reference/v2/payments-api/update-payment
> 
> Do not know whether is related to this onetime, of previous subscriptions (There is no webhook_url for payment_update in the cashier)

The response means that the provided parameter for webhook_url points to an URL that is unreachable which probably means that you didn’t make your app public through service like ngrok or expose before creating a Payment via the API.

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
