### ISSUE TITLE
Plan name is not changed while swapping

### ISSUE THREAD

**Issue by core45** [mollie/laravel-cashier-mollie#38]
A couple of weeks ago I did a pull request with small change in Subscription class.
It was this one:  While swapping plans the name should be also changed (not only 'plan' attribute/db column)

It's been accepted. I can see it in the code on the GitHub but when I update the package (or do fresh install) it's not there.
I really need it working.
Do I do something wrong?

I'd also be very honored if you add me to the contributors list :)

**Comment by Mul-tiMedia** [comment]
Hi @core45 i looks like the version number has not been bumped. @sandervanhooft

you could try using `dev-master` as version in your composer to get the latest commits.

You are not listed in the contributors page because your commits are not related to your GitHub account. It’s `core45@someip` instead of a commit with your e-mail address..

**Comment by sandervanhooft** [comment]
Here you go!

https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.0.5
