### ISSUE TITLE
Event listeners don't get triggered?

### ISSUE THREAD

**Issue by iqfx** [mollie/laravel-cashier-mollie#75]
Hello, it is probably me just not understanding even listeners quite right,

But using the test key I can't seem to trigger the event after a succesfull payment.
The webhook does get called and updates the payment status in the database.
For this instance I'm using a onetime charge payment.

My listener looks like this:
```
namespace App\Listeners;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Laravel\Cashier\Events\OrderPaymentPaid;
use Illuminate\Support\Facades\Log;

class ProcessPayment
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  OrderPaymentPaid  $event
     * @return void
     */
    public function handle(OrderPaymentPaid $event)
    {
        Log::info($event);
    }
}
```
In the example I'm just logging the the event in the log file, but that doesn't happen. I also tried just logging a simple string and that didn't work either. I also tried sending emails, as that is the intended use case to begin with.

One last question is to get the owner / user of the transaction, I presume I can just use $event->payments->owner ?
Please correct me if I'm wrong with that.

**Comment by sandervanhooft** [comment]
Hi @iqfx ,

Have you tried manually registering the event/listeners? https://laravel.com/docs/9.x/events#manually-registering-events

**Comment by ixperiencenl** [comment]
Same here. I registered the eventListener in my EventServiceProvider
`Event::listen(function (OrderPaymentFailed $event) {
            \Log::error(get_class($this) . ': Order payment failed event fired', ['event' => $event]);
            // Mail::to($request->user())->queue(new OrderPaymentFailed($order->number));
        });`

However, the OrderCreated event DOES get fired. Maybe the webhook doesn't work correctly (I use ngrok tunnel for this and that says 200OK)....

**Comment by iqfx** [comment]
> Hi @iqfx ,
> 
> Have you tried manually registering the event/listeners? https://laravel.com/docs/9.x/events#manually-registering-events

I tried this, but this made no difference unfortunately.

**Comment by sandervanhooft** [comment]
Let me see if I can reproduce this issue and get back to you.

**Comment by sandervanhooft** [comment]
We've looked into this on our end and I think the difference between First Payment events and Mandated Payment events could be the cause here. On this point the docs could use some improvement. And perhaps in v3 we could improve some naming (not entirely sure yet).

Simply put the events for first payments differ a bit from those for the mandated payments. This is a design consideration because the ramifications within payment/billing processes are slightly different.

FirstPaymentFailed / ...Paid relates to a first payment.

OrderPaymentFailed / ...Paid relates to a mandated payment.

If you're looking for one event that gets triggered when a first payment get paid and when a mandated payment gets paid, listen for the `OrderInvoiceAvailable` event ([docs](https://www.cashiermollie.com/09-events.html#orderinvoiceavailable-event)).
