### ISSUE TITLE
Changing plans within trial period

### ISSUE THREAD

**Issue by turpoint** [mollie/laravel-cashier-mollie#79]
I create subscription for teams using the following code. This gives them a one month trial period (for 1 EUR).

```
$result = $team->newSubscription('main', $plan, [
    'redirectUrl' => route('account.teams.subscriptions.index', [
        'team' => $team,
    ])
])
  ->trialUntil(Carbon::now()->addMonths(1))
  ->create();
```

To change / swap subscriptions, I use the following:

```
$subscription->swap($newPlan);
```

The problem is the following. Let's say the user starts a trial subscription on the "Bronze" plan, which should last him 1 month. If he upgrades to silver even weeks before his trial ends, he gets charged the full amount. And if he upgrades immediately after that to the gold plan, he also gets charged in full for the gold plan. So if he starts a trial subscription for bronze, and then immediately upgrades to silver, then gold, then diamond, he pays for all three.

This only happens during the trial period. Once that one ends, everything seems to work fine.

Is there someone with the same issue?

**Comment by sandervanhooft** [comment]
Two things at play here:

- the trial gets canceled when the customer swaps to a different plan. That is by design. Alternatively, consider using a generic trial ([docs](https://www.cashiermollie.com/03-trials.html#without-mandate-upfront))

- swapping between non-trial plans results in a full charge for the new plan, plus a reimbursement for the amount overcharged for the previous plan. Feel free to open a new ticket if this does not function as such.
