### ISSUE TITLE
One time charge - Force to Checkout

### ISSUE THREAD

**Issue by robertpotkowa** [mollie/laravel-cashier-mollie#86]
How it is possible every time, force the user to go thru the checkout process?

**Comment by christianschoenmakers** [comment]
Use case: you're selling subscriptions and offline (physical) product add-ons. 

The customers first payment is done by iDeal, so renewals of the subscription are paid by Sepa. 

If the customer buys an offline product, this order is created as single-charge. But you don't want this order to be paid by Sepa, because this is refundable. Instead, you want a separate iDeal transaction for this specific order. 

If you start a new first payment, you get a new mandate and upcoming renewals will be charged on this payment method? This is not ideal, I can imagine the customer is not aware of this change and he may use a different payment method than the recurring payments. 

Ideally you want to check first what payment method is assigned to the mandate (so on Sepa you want to create a separate payment, but on creditcard you just want to charge the creditcard).

**Comment by christianschoenmakers** [comment]
About the last comment, this is possible already by using the `mollieMandate` method.
